"""The identity a vocabulary's pages wear.

A generated site is not anonymous. A published vocabulary belongs to a
project, and the people who knew it by its logo should still recognise it
when the pages are regenerated by a different tool twelve years later. That
is the whole of this module: a logo, a name, the project it points at, and a
line that says whose work it is.

It is deliberately small, and deliberately not a theme system. Two colours
are accepted because a header painted in a palette that fights the logo looks
worse than no logo at all; everything else about the page stays as
``render.STYLE`` has it.

    brand = Brand.load("brand.yml")
    render_index(source, brand=brand)
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Brand:
    #: shown beside the logo, and as the alt text if the image does not load
    name: str = ""
    #: the logo, as a URL *relative to a page* — the pages of a served
    #: vocabulary all resolve relatively, so "static/logo.png" works whether
    #: the site is mounted at "/" or at "/seas/"
    logo: str = ""
    #: where the logo links: the project, not the vocabulary
    home: str = ""
    #: one line in the footer — who made this, under which programme
    note: str = ""
    #: the header background, and the colour of links.  Empty keeps the
    #: stylesheet's own.
    ink: str = ""
    accent: str = ""

    @classmethod
    def load(cls, path):
        """Read a brand from a small YAML file; unknown keys are refused
        rather than ignored, because a silently dropped `logo:` is a logo
        that never appears and nobody knows why."""
        import yaml
        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        if not isinstance(data, dict):
            raise ValueError("%s: a brand is a mapping" % path)
        known = {f for f in cls.__dataclass_fields__}
        unknown = sorted(set(data) - known)
        if unknown:
            raise ValueError("%s: unknown key(s) %s; known are %s"
                             % (path, ", ".join(unknown),
                                ", ".join(sorted(known))))
        return cls(**{k: str(v) for k, v in data.items()})

    def __bool__(self):
        return bool(self.name or self.logo or self.note)
